sudo: required
services:
  - docker

before_install:
  - docker build -t devopsdmc/React-Docker -f Dockerfile.dev .

script:
  - docker run -e CI=true devopsdmc/React-Docker npm run test -- --coverage
